api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "quantity-break-function"
type = "function"
uid = "7db942c5-58bc-8618-2a80-68890f553825a22f91aa"
description = "t:description"

  [[extensions.targeting]]
  target = "purchase.product-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
